entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: {}

api:
  dashboard: true
  insecure: true

providers:
  file:
    filename: /etc/traefik/providers.yaml
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    network: forseti_network

accessLog: {}

experimental:
  otlpLogs: true
log:
  level: INFO
  otlp:
    serviceName: "traefik"
    grpc:
      endpoint: "alloy:4317"
      insecure: true

metrics:
  otlp:
    serviceName: "traefik"
    pushInterval: "15s"
    grpc:
      endpoint: "alloy:4317"
      insecure: true

tracing:
  serviceName: "traefik"
  otlp:
    grpc:
      endpoint: "alloy:4317"
      insecure: true
