spring:
  config:
    import: classpath:core.yml
  application:
    name: forseti-autojudge
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  quartz:
    auto-startup: false
security:
  member-login: ${HOSTNAME:unknown}
  member-type: AUTOJUDGE