spring:
  config:
    import: classpath:core.yml
  application:
    name: forseti-autojudge
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  quartz:
    properties:
      org.quartz.threadPool.threadCount: 0
security:
  member-id: 22222222-2222-2222-2222-222222222222