[versions]
bcrypt = "0.10.2"
flyway = "9.22.3"
hibernate-envers = "6.6.13.Final"
hibernate-types = "2.21.1"
jackson = "2.18.3"
java-diff-utils = "4.15"
kotest = "5.9.1"
kotest-extensions-spring = "1.3.0"
kotlin = "2.1.20"
kover = "0.9.1"
ktlint = "14.0.1"
minio = "8.5.17"
mockk = "1.13.17"
socketio = "2.0.13"
opencsv = "5.11"
opentelemetry = "1.56.0"
opentelemetry-mdc = "2.11.0-alpha"
postgresql = "42.7.5"
prometheus = "1.4.3"
snakeyaml = "2.4"
spring-boot = "3.4.5"
springmockk = "4.0.2"
testcontainers = "1.21.0"
testcontainers-redis = "2.2.2"
uuid-creator = "6.1.1"

[libraries]
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }
hibernate-envers = { module = "org.hibernate.orm:hibernate-envers", version.ref = "hibernate-envers" }
hibernate-types = { module = "com.vladmihalcea:hibernate-types-60", version.ref = "hibernate-types" }
flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
jackson-datatype-jsr310 = { module = 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310', version.ref = "jackson" }
jackson-module-kotlin = { module = 'com.fasterxml.jackson.module:jackson-module-kotlin', version.ref = "jackson" }
java-diff-utils = { module = 'io.github.java-diff-utils:java-diff-utils', version.ref = "java-diff-utils" }
kotest-assertions-core = { module = 'io.kotest:kotest-assertions-core', version.ref = "kotest" }
kotest-runner-junit5 = { module = 'io.kotest:kotest-runner-junit5', version.ref = "kotest" }
kotest-extensions-spring = { module = 'io.kotest.extensions:kotest-extensions-spring', version.ref = "kotest-extensions-spring" }
kotlin-reflect = { module = 'org.jetbrains.kotlin:kotlin-reflect', version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
minio = { module = "io.minio:minio", version.ref = "minio" }
netty-socketio = { module = "com.corundumstudio.socketio:netty-socketio", version.ref = "socketio" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry" }
opentelemetry-instrumentation-logback-mdc = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-mdc-1.0", version.ref = "opentelemetry-mdc" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
prometheus-metrics-core = { module = "io.prometheus:prometheus-metrics-core", version.ref = "prometheus" }
prometheus-metrics-exporter-servlet-jakarta = { module = "io.prometheus:prometheus-metrics-exporter-servlet-jakarta", version.ref = "prometheus" }
prometheus-metrics-instrumentation-jvm = { module = "io.prometheus:prometheus-metrics-instrumentation-jvm", version.ref = "prometheus" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
spring-boot-dev-tools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "spring-boot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring-boot" }
spring-boot-starter-amqp = { module = "org.springframework.boot:spring-boot-starter-amqp", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis", version.ref = "spring-boot" }
spring-boot-starter-quartz = { module = "org.springframework.boot:spring-boot-starter-quartz", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-websocket = { module = "org.springframework.boot:spring-boot-starter-websocket", version.ref = "spring-boot" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "spring-boot" }
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgres = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-minio = { module = "org.testcontainers:minio", version.ref = "testcontainers" }
testcontainers-rabbitmq = { module = "org.testcontainers:rabbitmq", version.ref = "testcontainers" }
testcontainers-redis = { module = "com.redis:testcontainers-redis", version.ref = "testcontainers-redis" }
uuid-creator = { module = "com.github.f4b6a3:uuid-creator", version.ref = "uuid-creator" }

[bundles]
jackson = [
    "jackson-datatype-jsr310",
    "jackson-module-kotlin"
]
kotest = [
    "kotest-assertions-core",
    "kotest-runner-junit5",
]
mockk = [
    "mockk",
    "springmockk"
]
opentelemetry = [
    "opentelemetry-api",
    "opentelemetry-instrumentation-logback-mdc"
]
prometheus = [
    "prometheus-metrics-core",
    "prometheus-metrics-exporter-servlet-jakarta",
    "prometheus-metrics-instrumentation-jvm"
]
spring = [
    "spring-boot-starter",
    "spring-boot-starter-actuator",
    "spring-boot-starter-amqp",
    "spring-boot-starter-data-jpa",
    "spring-boot-starter-data-redis",
    "spring-boot-starter-quartz",
    "spring-boot-starter-validation",
    "spring-boot-starter-web",
]
spring-test = [
    "kotest-extensions-spring",
    "spring-boot-starter-test",
]
testcontainers = [
    "spring-boot-testcontainers",
    "testcontainers-junit-jupiter",
    "testcontainers-postgres",
    "testcontainers-minio",
    "testcontainers-rabbitmq",
    "testcontainers-redis"
]

[plugins]
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
spring = { id = "org.springframework.boot", version.ref = "spring-boot" }
