spring:
  config:
    import: classpath:core.yml
  application:
    name: forseti-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
security:
  member-login: ${HOSTNAME:unknown}
  member-type: API