spring:
  config:
    import: classpath:core-production.yml
server:
  cors:
    allowed-origins: ${WEBAPP_PUBLIC_URL:https://forsetijudge.com}
  port: ${API_PORT:8080}
  ws-port: ${WS_PORT:8081}
security:
  cookie:
    domain: ${COOKIE_DOMAIN:.forsetijudge.com}
    secure: ${COOKIE_SECURE:true}
