apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: ${LOKI_URL}
    editable: false
    version: 1

  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    editable: false
    uid: prometheus
    jsonData:
      httpMethod: GET
    version: 1

  - name: Tempo
    type: tempo
    access: proxy
    url: ${TEMPO_URL}
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: "prometheus"
    editable: false
    version: 1

  - name: Postgres
    type: postgres
    access: proxy
    url: ${DB_URL}
    database: ${DB_NAME}
    user: ${DB_USER}
    jsonData:
      sslmode: disable
    secureJsonData:
      password: ${DB_PASSWORD}
    editable: false
    version: 1
