apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: ${LOKI_URL}
    version: 1
    editable: false

  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    version: 1
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    url: ${TEMPO_URL}
    version: 1
    editable: false

  - name: Postgres
    type: postgres
    access: proxy
    url: ${DB_URL}
    database: ${DB_NAME}
    user: ${DB_USER}
    jsonData:
      sslmode: disable
    secureJsonData:
      password: ${DB_PASSWORD}
    version: 1
    editable: false
